stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocess:
    cmd: python src/preprocessing.py
    deps:
    - data/raw
    - src/preprocessing.py
    outs:
    - data/interim

  feature_engg:
    cmd: python src/featureeng.py
    deps:
    - data/interim
    - src/featureeng.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed

  model_creation:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl

  model_evaulation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
#     metrics:
#     - reports/metrics.json
# metrics:
# - dvclive/metrics.json
# plots:
# - dvclive/plots/metrics:
#     x: step
# metrics:
# - dvclive/metrics.json
# plots:
# - dvclive/plots/metrics:
#     x: step
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
